In [1]:
import numpy as np

In [2]:
my_list= [1,2,3]
type(my_list)

list

In [3]:
#convert a list ot numpy array
np.array(my_list)

array([1, 2, 3])

In [4]:
#convert a 2D list to numpy array
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#Linear spaced array
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
#Create an indentiy matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr= np.arange(25)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr.max()

24

In [19]:
arr.argmax()

24

In [20]:
list = [34,56,78,8,99,0,67,99,123,456,345]
my_list = np.array(list)

In [21]:
my_list.argmax()

9

In [22]:
srr = np.arange(0,11)

In [23]:
srr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
srr[0:5]=99

In [25]:
srr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
srr_copy = srr.copy()

In [27]:
srr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [28]:
srr_copy[:]=100

In [29]:
srr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [42]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
arr_2d = np.array(my_matrix)

In [41]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [43]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr_2d[1,1]

5