In [1]:
#import the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
#Linear regression with multiple variables. Area, bedrooms,age are the dependent variables and price is the dependent variable.
# y = m1*area+m2*bedrooms+m3*age+b

df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age  price
0  1500       3.0   30     60
1  1200       2.0   35     50
2  2000       NaN   30     75
3  1800       3.0   40     45
4  1600       NaN   30     62

In [6]:
#there are few null values in bedrooms column. We can replace null values by using median value
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

3

In [7]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age  price
0  1500       3.0   30     60
1  1200       2.0   35     50
2  2000       3.0   30     75
3  1800       3.0   40     45
4  1600       3.0   30     62

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
reg.coef_

array([  0.03071429, -11.55952381,  -2.37380952])

In [10]:
reg.intercept_

119.34523809520866

In [13]:
reg.predict([[3000,3,5]])

array([164.94047619])

In [14]:
reg.predict([[3000,3,50]])

array([58.11904762])